---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'emass_client/ruby_client/**/*'
    - Gemfile
    - Rakefile
    - 'test/**/*'

#Cops in Metrics might need to be adjusted to past their defaults depending on how restrictive the requirements feel
Style/Documentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
Style/Encoding:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 10
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Layout/HashAlignment:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
